"""Backend exam-question DTO (WP17 section 6).

One uniform shape for every question that appears in an assembled exam, whether
it was selected from the database (``origin="database"``) or generated by the
pinned generator (``origin="llm"``).

Guarantees:

* the seven public fields are always present:
  ``number, question, answer1..4, correct_answer``;
* ``instance_id`` is unique per exam position; ``id`` is the DB primary key or
  ``None`` for generated questions;
* ``category`` is the canonical spelling this position's quota belongs to;
* LLM questions carry null/empty performance defaults;
* ``generation_meta`` (attempts / retries / cost) is present for LLM questions
  and is EXCLUDED from anything that becomes DOCX content -- use
  :meth:`ExamQuestionDTO.docx_view`.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from typing import Any, Literal, Optional

__all__ = ["ExamQuestionDTO", "GenerationMeta", "SEVEN_PUBLIC_FIELDS"]

SEVEN_PUBLIC_FIELDS = (
    "number",
    "question",
    "answer1",
    "answer2",
    "answer3",
    "answer4",
    "correct_answer",
)


@dataclass(frozen=True)
class GenerationMeta:
    """Non-content provenance for a generated question. Never in DOCX output."""

    attempts: int = 0
    retries_by_slot: int = 0
    cost_usd: str = "0"
    was_repaired: bool = False
    reviewer_confidence: Optional[float] = None
    audit_ref: Optional[str] = None
    outcome: str = "accepted"

    def to_dict(self) -> dict:
        return {
            "attempts": self.attempts,
            "retries_by_slot": self.retries_by_slot,
            "cost_usd": self.cost_usd,
            "was_repaired": self.was_repaired,
            "reviewer_confidence": self.reviewer_confidence,
            "audit_ref": self.audit_ref,
            "outcome": self.outcome,
        }


@dataclass
class ExamQuestionDTO:
    # --- seven public fields ---------------------------------------------------
    number: int
    question: str
    answer1: str
    answer2: str
    answer3: str
    answer4: str
    correct_answer: int

    # --- identity ------------------------------------------------------------
    origin: Literal["database", "llm"] = "database"
    instance_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    id: Optional[int] = None  # DB primary key, or None for generated questions

    # --- categorisation (canonical spelling) --------------------------------
    category: str = ""          # the quota this position satisfies
    primary_category: str = ""  # DB primary category (== category for LLM)
    categories: list = field(default_factory=list)

    # --- performance (null/empty for LLM) ---------------------------------
    accuracy: Optional[float] = None
    distinction: Optional[float] = None
    accuracy_list: list = field(default_factory=list)
    distinction_list: list = field(default_factory=list)

    # --- provenance (excluded from DOCX) ----------------------------------
    generation_meta: Optional[GenerationMeta] = None

    def __post_init__(self) -> None:
        if self.correct_answer not in (1, 2, 3, 4):
            raise ValueError("correct_answer must be 1..4")
        for f in ("question", "answer1", "answer2", "answer3", "answer4"):
            if not isinstance(getattr(self, f), str) or not getattr(self, f).strip():
                raise ValueError(f"{f} must be a non-empty string")
        if not self.categories:
            self.categories = [self.category] if self.category else []
        if not self.primary_category:
            self.primary_category = self.category
        if self.origin == "llm":
            # LLM questions never carry performance history.
            self.accuracy = None
            self.distinction = None
            self.accuracy_list = []
            self.distinction_list = []
            if self.id is not None:
                raise ValueError("generated (llm) questions must have id=None")
            if self.generation_meta is None:
                self.generation_meta = GenerationMeta()

    # --- constructors ------------------------------------------------------
    @classmethod
    def from_db_question(cls, q: Any, *, number: int, category: str) -> "ExamQuestionDTO":
        """Build from a ``src.models.question.Question`` row."""
        return cls(
            number=number,
            question=q.question,
            answer1=q.answer1,
            answer2=q.answer2,
            answer3=q.answer3,
            answer4=q.answer4,
            correct_answer=q.correct_answer_id,
            origin="database",
            id=q.id,
            category=category,
            primary_category=q.category,
            categories=list(q.categories),
            accuracy=q.accuracy,
            distinction=q.distinction,
            accuracy_list=list(q.accuracy_list),
            distinction_list=list(q.distinction_list),
        )

    @classmethod
    def from_generated(
        cls,
        seven_fields: dict,
        *,
        number: int,
        category: str,
        generation_meta: Optional[GenerationMeta] = None,
    ) -> "ExamQuestionDTO":
        """Build from a generator seven-field public question dict."""
        missing = [f for f in SEVEN_PUBLIC_FIELDS if f not in seven_fields]
        if missing:
            raise ValueError(f"generated question missing public fields: {missing}")
        return cls(
            number=number,
            question=seven_fields["question"],
            answer1=seven_fields["answer1"],
            answer2=seven_fields["answer2"],
            answer3=seven_fields["answer3"],
            answer4=seven_fields["answer4"],
            correct_answer=seven_fields["correct_answer"],
            origin="llm",
            id=None,
            category=category,
            primary_category=category,
            categories=[category],
            generation_meta=generation_meta or GenerationMeta(),
        )

    # --- views -----------------------------------------------------------------
    def public_seven(self) -> dict:
        return {f: getattr(self, f) for f in SEVEN_PUBLIC_FIELDS}

    def docx_view(self) -> dict:
        """Exactly what DOCX rendering may see: seven fields + display category.

        ``generation_meta`` is deliberately absent.
        """
        view = self.public_seven()
        view["category"] = self.category
        return view

    def to_dict(self) -> dict:
        d = {
            **self.public_seven(),
            "origin": self.origin,
            "instance_id": self.instance_id,
            "id": self.id,
            "category": self.category,
            "primary_category": self.primary_category,
            "categories": list(self.categories),
            "accuracy": self.accuracy,
            "distinction": self.distinction,
            "accuracy_list": list(self.accuracy_list),
            "distinction_list": list(self.distinction_list),
        }
        if self.generation_meta is not None:
            d["generation_meta"] = self.generation_meta.to_dict()
        return d
